default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("PGUSER", `whoami`.strip) %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

development:
  <<: *default
  database: close_leads_app_development

test:
  <<: *default
  database: close_leads_app_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

cable:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

queue:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
